spring.application.name=facthub-service

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL - AIVEN CLOUD)
# ===============================
spring.datasource.url=jdbc:postgresql://facthub-facthub.d.aivencloud.com:13247/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=<TU_PASSWORD_AQUI>
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl-auto (update para desarrollo, validate para producción)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURACIÓN DE SEARCHPE API
# ===============================
searchpe.api.url=https://searchpe-atelier.onrender.com
